### PR TITLE
Bump hawthorn dependency to 1.2.7

### PR DESCRIPTION
**Pull request by joshbwlng**
Change-type: patch
Signed-off-by: Josh Bowling <josh@balena.io>

### CODE REVIEW

**Comment by joshbwlng** [comment]
@jviotti Here's the last bump needed to patch the vulnerability in `deplint` I mentioned in https://github.com/jviotti/hawthorn/pull/18. Thanks!

**Comment by jviotti** [comment]
Deployed to npm as v1.1.3

**Comment by joshbwlng** [comment]
@jviotti Thanks! And I noticed you enabled dependabot, good idea. I could help managing this repo if you need it.

**Comment by jviotti** [comment]
@joshbwlng Sure, sounds good! I'll add you as a collaborator on GitHub. Let me know what your npm username is so I can add you as a collaborator there as well!

**Comment by jviotti** [comment]
Done! You should be able to publish the package to npm yourself if needed!

**Pull request merged**
